[package]
name = "key_value_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0.30"
# hyper = "0.14.15"
# tokio = "1.14.*"
